from vk_api.bot_longpoll import VkBotEventType


MENTION = ":::CANARYBOT:MENTION:::"
ENDLINE = ":::CANARYBOT:ENDMESSAGE:::"
ACTION = ":::CANARYBOT:ACTION:::"
PAYLOAD = ":::CANARYBOT:PAYLOAD:::"
NOREACT = ":::CANARYBOT:NOREACT:::"
START_LOGGER = "logging is started"

MESSAGE_NEW = VkBotEventType.MESSAGE_NEW
MESSAGE_ALLOW = VkBotEventType.MESSAGE_ALLOW
MESSAGE_DENY = VkBotEventType.MESSAGE_DENY
MESSAGE_EVENT = VkBotEventType.MESSAGE_EVENT

PHOTO_NEW = VkBotEventType.PHOTO_NEW
PHOTO_COMMENT_NEW = VkBotEventType.PHOTO_COMMENT_NEW
PHOTO_COMMENT_EDIT = VkBotEventType.PHOTO_COMMENT_EDIT
PHOTO_COMMENT_RESTORE = VkBotEventType.PHOTO_COMMENT_RESTORE
PHOTO_COMMENT_DELETE = VkBotEventType.PHOTO_COMMENT_DELETE

AUDIO_NEW = VkBotEventType.AUDIO_NEW

VIDEO_NEW = VkBotEventType.VIDEO_NEW
VIDEO_COMMENT_NEW = VkBotEventType.VIDEO_COMMENT_NEW
VIDEO_COMMENT_EDIT = VkBotEventType.VIDEO_COMMENT_EDIT
VIDEO_COMMENT_RESTORE = VkBotEventType.VIDEO_COMMENT_RESTORE
VIDEO_COMMENT_DELETE = VkBotEventType.VIDEO_COMMENT_DELETE

WALL_POST_NEW = VkBotEventType.WALL_POST_NEW
WALL_REPOST = VkBotEventType.WALL_REPOST
WALL_REPLY_NEW = VkBotEventType.WALL_REPLY_NEW
WALL_REPLY_EDIT = VkBotEventType.WALL_REPLY_EDIT
WALL_REPLY_RESTORE = VkBotEventType.WALL_REPLY_RESTORE
WALL_REPLY_DELETE = VkBotEventType.WALL_REPLY_DELETE

BOARD_POST_NEW = VkBotEventType.BOARD_POST_NEW
BOARD_POST_EDIT = VkBotEventType.BOARD_POST_EDIT
BOARD_POST_RESTORE = VkBotEventType.BOARD_POST_RESTORE
BOARD_POST_DELETE = VkBotEventType.BOARD_POST_DELETE
BEEPA_PAPASA = ":::NYASHKA:NYASHKA:::"

MARKET_COMMENT_NEW = VkBotEventType.MARKET_COMMENT_NEW
MARKET_COMMENT_EDIT = VkBotEventType.MARKET_COMMENT_EDIT
MARKET_COMMENT_RESTORE = VkBotEventType.MARKET_COMMENT_RESTORE
MARKET_COMMENT_DELETE = VkBotEventType.MARKET_COMMENT_DELETE
MARKET_ORDER_NEW = ":::CANARYBOT:MARKET_ORDER_NEW:::"
MARKET_ORDER_EDIT = ":::CANARYBOT:MARKET_ORDER_EDIT:::"

GROUP_LEAVE = VkBotEventType.GROUP_LEAVE
GROUP_JOIN = VkBotEventType.GROUP_JOIN

USER_BLOCK = VkBotEventType.USER_BLOCK
USER_UNBLOCK = VkBotEventType.USER_UNBLOCK

POLL_VOTE_NEW = VkBotEventType.POLL_VOTE_NEW

GROUP_OFFICERS_EDIT = VkBotEventType.GROUP_OFFICERS_EDIT
GROUP_CHANGE_SETTINGS = VkBotEventType.GROUP_CHANGE_SETTINGS
GROUP_CHANGE_PHOTO = VkBotEventType.GROUP_CHANGE_PHOTO

VKPAY_TRANSACTION = VkBotEventType.VKPAY_TRANSACTION
APP_PAYLOAD = ":::CANARYBOT:APP_PAYLOAD:::"

LIKE_ADD = ":::CANARYBOT:LIKEADD:::"
LIKE_REMOVE = ":::CANARYBOT:LIKEREMOVE:::"


PLUGIN_LOAD = "plugin list is loaded, to update use \"self.all = self.getPlugins()\""
PLUGIN_INIT = "initialisation"

PLUGIN_FAILED_BROKEN = "Broken ({})"
PLUGIN_FAILED_NOSUPP = "Plugin version is not supported"
PLUGIN_FAILED_NOUPD = "No 'update' function"
CONSOLE_SYNTAX = ""

ERROR_HANDLER = ":::CANARYBOT:ERROR_HANDLER:::"

LIBRARY_SYNTAX = ":::CANARYBOT:LIBRARY_SYNTAX:::"
PARSER_SYNTAX = ":::CANARYBOT:PARSER:::"

ASSETS_ERROR = ""

LIBRARY_ERROR = ":::CANARYBOT:LIBRARY_ERROR:::"
LIBRARY_NOSELECT = ":::CANARYBOT:LIBRARY_NOSELECT:::"
LIBRARY_PIC = ""

LIBRARY_RESPONSE_LIST = ""
LIBRARY_RESPONSE_LIST_ITEM = ""
LIBRARY_RESPONSE_ERROR = ""
LIBRARY_RESPONSE_DESCR = "{name} ({ver}): {descr}"


class responses:
    def __init__(self):
        pass